project: 
  name: "sistema-noticia"
  port: "4083"
database:
  host: "postgresql-server-hardprox.cn62zsakc6gw.sa-east-1.rds.amazonaws.com"
  user: "GoUser"
  pswd: "gouser"
  dbnm: "db-news"
  port: "5432"